<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>비동기작업</title>
</head>
<body>
<h1>Promise - 예외처리: Method Chaining II</h1>
<script>
const promise = new Promise((resolve, reject) => {
  // resolve();
  // reject();
  throw '오류 발생!!!';
})
.then(() => console.log("fulfilled! - 1"))
.then(() => console.log("fulfilled! - 2"))
.catch(() => console.log("catched! - 1"))
.catch(() => console.log("catched! - 2"))
.then(() => console.log("fulfilled! - 3"))
.then(() => console.log("fulfilled! - 4"));


console.log("끝!");

</script>
</body>
</html>